name: 📦 Update Knowledge Graphs

on:
  schedule:
    - cron: '0 4 * * *'  # tous les jours à 4h UTC
  workflow_dispatch:     # permet de le lancer manuellement depuis l'interface GitHub
  push:
    paths:
      - 'cskg/**'
      - '.github/workflows/update_kg.yml'

jobs:
  update-kg:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout du code
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: 📦 Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ⚙️ Exécuter le pipeline KG
        run: |
          python cskg/collect_nvd.py
          python cskg/extract_nessus.py
          python cskg/align_kg.py
          python cskg/fuse_kg.py
          python cskg/update_neo4j.py
